# Generated by Django 3.1.4 on 2021-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('Type-1', 'Type-1'), ('Type-2', 'Type-2'), ('Type-3', 'Type-3'), ('Type-4', 'Type-4'), ('Type-5', 'Type-5'), ('Type-6', 'Type-6'), ('Type-7', 'Type-7')], max_length=30, verbose_name='Choose Image Type'),
        ),
    ]
