# Generated by Django 3.1.4 on 2021-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210220_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('Type1', 'Type1'), ('Type2', 'Type2'), ('Type3', 'Type3'), ('Type4', 'Type4'), ('Type5', 'Type5'), ('Type6', 'Type6'), ('Type7', 'Type7')], max_length=30, verbose_name='Choose Image Type'),
        ),
    ]
